name: Push, pull and automations
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@main
        id: lokalise-push
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 8395245768e7e07fd330a5.85523356
          base_lang: en
          translations_path: |
            locales
            i18n
          file_format: json
          file_ext: json
          additional_params: >
            {
              "convert_placeholders": true
            }

      - name: Debug Push Outputs
        run: |
          echo "Initial Run: ${{ steps.lokalise-push.outputs.initial_run }}"
          echo "Files Uploaded: ${{ steps.lokalise-push.outputs.files_uploaded }}"

      - name: Pull from Lokalise
        id: lokalise-pull
        uses: lokalise/lokalise-pull-action@handle_on_pr_trigger
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 8395245768e7e07fd330a5.85523356
          translations_path: |
            locales
            i18n
          file_format: json
          file_ext: json
          pr_draft: true
          async_mode: true

      - name: Debug Pull Outputs
        run: |
          echo "Branch used:   ${{ steps.lokalise-pull.outputs.created_branch }}"
          echo "PR exists:     ${{ steps.lokalise-pull.outputs.pr_exists }}"
          echo "PR created:    ${{ steps.lokalise-pull.outputs.pr_created }}"
          echo "PR updated:    ${{ steps.lokalise-pull.outputs.pr_updated }}"
          echo "PR action:     ${{ steps.lokalise-pull.outputs.pr_action }}"
          echo "PR number:     ${{ steps.lokalise-pull.outputs.pr_number }}"
          echo "PR id:         ${{ steps.lokalise-pull.outputs.pr_id }}"
          echo "PR url:        ${{ steps.lokalise-pull.outputs.pr_url }}"